package ProyectoFiguras_U4;
import ProyectoFiguras.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
public class IFrameTrianguloEq extends javax.swing.JInternalFrame implements ActionListener{
    CTrianguloEq A = new CTrianguloEq();
    private JLabel lado;
    private JTextField txtLado;
    private JTextArea resultados;
    private JButton calcular;
    public IFrameTrianguloEq() {
        initComponents();
        setLayout(null);
        lado = new JLabel("Lado:");
        lado.setBounds(10,10,200,30);
        lado.setFont(new Font("Andale Mono",2,18));
        add(lado);
        txtLado = new JTextField();
        txtLado.setBounds(80,10,100,30);
        txtLado.setFont(new Font("Andale Mono",0,18));
        add(txtLado);
        resultados = new JTextArea();
        resultados.setBounds(25,120,400,100);
        resultados.setEditable(false);
        resultados.setFont(new Font("Andale Mono",2,18));
        resultados.setForeground(Color.black);
        add(resultados);
        calcular = new JButton("Calcular");
        calcular.setBounds(100,225,130,40);
        calcular.setFont(new Font("Andale Mono",1,18));
        calcular.addActionListener(this);
        add(calcular);
    }
    public void actionPerformed(ActionEvent e){
        int l1;
        String area="",perimetro="";
        try{
            if (e.getSource()==calcular) {
                l1=Integer.parseInt(txtLado.getText());
                if (l1==0) {
                    JOptionPane.showMessageDialog(this, "Ingresa valor diferente de 0");
                    txtLado.setText("");
                    resultados.setText("");
                }
                else{
                    A.setLado1(l1);
                    A.Area();
                    A.Perimetro();
                    area="Área= "+A.getArea()+"u²";
                    perimetro="Perímetro= "+A.getPerimetro()+"u";
                    resultados.setText(area+"\n"+perimetro);
                }
            }
        }catch(NumberFormatException f){
            JOptionPane.showMessageDialog(this, "Ingresar solo valores numericos");
            txtLado.setText("");
            resultados.setText("");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
