package ProyectoFiguras_U4;
import ProyectoFiguras.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
//@author Luis Ricardo Reyes Villar
public class IFrameRombo extends javax.swing.JInternalFrame implements ActionListener {
    CRombo A = new CRombo();
    private JLabel diagMayor,diagMenor;
    private JTextField txtDiagMayor,txtDiagMenor;
    private JTextArea resultados;
    private JButton calcular;
    public IFrameRombo() {
        initComponents();
        setLayout(null);
        diagMayor = new JLabel("Diagonal Mayor:");
        diagMayor.setBounds(10,10,200,30);
        diagMayor.setFont(new Font("Andale Mono",2,18));
        add(diagMayor);
        diagMenor = new JLabel("Diagonal Menor:");
        diagMenor.setBounds(10,50,200,30);
        diagMenor.setFont(new Font("Andale Mono",2,18));
        add(diagMenor);
        txtDiagMayor = new JTextField();
        txtDiagMayor.setBounds(170,10,100,30);
        txtDiagMayor.setFont(new Font("Andale Mono",0,18));
        add(txtDiagMayor);
        txtDiagMenor = new JTextField();
        txtDiagMenor.setBounds(170,50,100,30);
        txtDiagMenor.setFont(new Font("Andale Mono",0,18));
        add(txtDiagMenor);
        resultados = new JTextArea();
        resultados.setBounds(25,120,400,100);
        resultados.setEditable(false);
        resultados.setFont(new Font("Andale Mono",2,18));
        resultados.setForeground(Color.black);
        add(resultados);
        calcular = new JButton("Calcular");
        calcular.setBounds(100,225,130,40);
        calcular.setFont(new Font("Andale Mono",1,18));
        calcular.addActionListener(this);
        add(calcular);
    }
    public void actionPerformed(ActionEvent e){
        try{
            int l1,l2;
            String area="",perimetro="";
            if (e.getSource()==calcular) {    
                l1=Integer.parseInt(txtDiagMayor.getText());
                l2=Integer.parseInt(txtDiagMenor.getText());
                if (l1<=l2) {
                    JOptionPane.showMessageDialog(this, "La Diagonal Mayor es el mayor valor introducible.\n"
                            + "No puede tener el mismo o menor valor que la diagonal menor.\nIngrese valores validos.");
                    txtDiagMayor.setText("");
                    txtDiagMenor.setText("");
                    resultados.setText("");
                }
                else if (l1==0||l2==0) {
                    JOptionPane.showMessageDialog(this, "Ingrese valores diferente de 0");
                    txtDiagMayor.setText("");
                    txtDiagMenor.setText("");
                    resultados.setText("");
                }
                else{
                    A.setLado1(l1);
                    A.setLado2(l2);
                    A.Perimetro();
                    A.Area();
                    area="Área= "+A.getArea()+"u²";
                    perimetro="Perímetro= "+A.getPerimetro()+"u";
                    resultados.setText(area+"\n"+perimetro);
                }
            }
        }catch(NumberFormatException f){
            JOptionPane.showMessageDialog(this, "Ingresar solo valores numericos");
            txtDiagMayor.setText("");
            txtDiagMenor.setText("");
            resultados.setText("");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}